apiVersion: apps/v1
kind: Deployment
metadata:
  name: "taw2aksjrc182-a924"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "taw2aksjrc182-a924"
  template:
    metadata:
      labels:
        app: "taw2aksjrc182-a924"
    spec:
      containers:
        - name: "taw2aksjrc182-a924"
          image: "taw2acrjrc182.azurecr.io/taw2aksjrc182"
          env:
            - name: CosmosDb__Account
              value: { { .Values.cosmosDb.account } }
            - name: CosmosDb__Key
              value: { { .Values.cosmosDb.key } }
            - name: CosmosDb__DatabaseName
              value: HealthCheckDB
            - name: CosmosDb__ContainerName
              value: HealthCheck
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /HealthCheck
              port: http
          readinessProbe:
            httpGet:
              path: /HealthCheck
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
